image: node:8.9.4
pipelines:
  branches:
    SOFT:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm test
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm test
      - step:
          name: Deploy to production
          image: kroniak/ssh-client
          deployment: production
          trigger: manual
          script:
            - cd scripts
            - bash updateRepo.sh
