version: '3'
services:
  hathsin:
    build: .
    container_name: hathsin
    ports:
      - 4000:4000
    volumes:
      - ./storage:/usr/src/app/storage

networks:
  default:
    external:
      name: webplatform_suilabs
