version: '3'
services:
  hathsin:
    build:
      context: service
    container_name: hathsinV2
    ports:
      - 4001:4000
    environment:
    - DB_SERVER=hathsin-database
    - DB_SCHEMA=hathsin
    - MONGO_USERNAME=$MONGO_USERNAME
    - MONGO_PASSWORD=$MONGO_PASSWORD
  hathsin-database:
    image: mongo:latest
    container_name: hathsin-database
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    - MONGO_INITDB_DATABASE=hathsin
    - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
    - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
    - ./db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --auth # --quiet

networks:
  default:
    external:
      name: webplatform_suilabs
