# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./service/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: |
        cd ./service
        npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./service/package.json" }}
      - run: |
          cd ./service
          npm test
      - run: |
          cd ./service
          npm build
  release:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - deploy:
          command: |
            sudo apt update
            sudo apt install -y rsync
            cd scripts
            bash updateRepo.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - release:
          filters:
            branches:
              only:
                - master
                - SOFT-28_AdminPage
          requires:
            - build
